/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpressosystems.xpresscashdrawer.view;

import com.xpressosystems.xpresscashdrawer.control.FramePrincipalControl;
import javax.swing.JButton;

/**
 *
 * @author alfredo
 */
public class DialogEdicionProducto extends javax.swing.JDialog {

	/**
	 * Creates new form PanelEdicionProducto
	 */
	public DialogEdicionProducto(String titulo) {
		
		super(FramePrincipalControl.getInstance().getFramePrincipal(), titulo, true);
		
		initComponents();
		campos = new javax.swing.JTextField[8];
		
		campos[0] = jTextField1;
		campos[1] = jTextField2;
		campos[2] = jTextField3;
		campos[3] = jTextField4;
		campos[4] = jTextField5;
		campos[5] = jTextField6;
		campos[6] = jTextField7;
		campos[7] = jTextField8;
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        surtirLbl = new javax.swing.JLabel();
        surtir = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        imagenProducto = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        cambiarFoto = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(8, 1));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("CODIGO :");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 19));
        jPanel4.add(jLabel1);

        jTextField1.setColumns(10);
        jTextField1.setToolTipText("Este es el CODIGO de Barras");
        jPanel4.add(jTextField1);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre :");
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 19));
        jPanel5.add(jLabel2);

        jTextField2.setColumns(25);
        jTextField2.setToolTipText("Solo en nombre y que contiene, ejemplo \"Chiles Chipotles 255 g.\"");
        jPanel5.add(jTextField2);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Linea :");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 19));
        jPanel6.add(jLabel3);

        jTextField3.setColumns(20);
        jTextField3.setToolTipText("Este es el tipo de producto (Cereales, Chiles, Paletas, Jabones, ..etc)");
        jPanel6.add(jTextField3);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Marca :");
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 19));
        jPanel7.add(jLabel4);

        jTextField4.setColumns(20);
        jTextField4.setToolTipText("La marca, ejemplo: Herdez, Bimbo, Coca-Cola");
        jPanel7.add(jTextField4);

        jPanel1.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Costo :");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 19));
        jPanel8.add(jLabel5);

        jTextField5.setColumns(5);
        jTextField5.setToolTipText("El costo neto de como se compro");
        jPanel8.add(jTextField5);

        jPanel1.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Precio Venta :");
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 19));
        jPanel9.add(jLabel6);

        jTextField6.setColumns(5);
        jTextField6.setToolTipText("El precio neto de cuanto se va a vender");
        jPanel9.add(jTextField6);

        jPanel1.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Piezas X Caja :");
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 19));
        jPanel10.add(jLabel7);

        jTextField7.setColumns(3);
        jTextField7.setToolTipText("El numero de Piezas por mayoreo en 1 caja o empaque");
        jPanel10.add(jTextField7);

        jPanel1.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Existencia :");
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 19));
        jPanel11.add(jLabel8);

        jTextField8.setColumns(3);
        jTextField8.setToolTipText("Piezas en almacén para vender");
        jPanel11.add(jTextField8);

        surtirLbl.setText("+ Surtir:");
        jPanel11.add(surtirLbl);

        surtir.setColumns(3);
        jPanel11.add(surtir);

        jPanel1.add(jPanel11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        aceptar.setText("Aceptar");
        jPanel3.add(aceptar);

        cancelar.setText("Cancelar");
        jPanel3.add(cancelar);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setPreferredSize(new java.awt.Dimension(210, 10));
        jPanel2.setLayout(new java.awt.BorderLayout());

        imagenProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(imagenProducto, java.awt.BorderLayout.CENTER);

        cambiarFoto.setText("Cambiar Foto");
        jPanel12.add(cambiarFoto);

        jPanel2.add(jPanel12, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        setSize(new java.awt.Dimension(641, 318));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cambiarFoto;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel imagenProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField surtir;
    private javax.swing.JLabel surtirLbl;
    // End of variables declaration//GEN-END:variables

	private javax.swing.JTextField[] campos;

	/**
	 * @return the aceptar
	 */
	public javax.swing.JButton getAceptar() {
		return aceptar;
	}

	/**
	 * @return the cancelar
	 */
	public javax.swing.JButton getCancelar() {
		return cancelar;
	}

	/**
	 * @return the campos
	 */
	public javax.swing.JTextField[] getCampos() {
		return campos;
	}

	/**
	 * @return the surtir
	 */
	public javax.swing.JTextField getSurtir() {
		return surtir;
	}

	/**
	 * @return the surtirLbl
	 */
	public javax.swing.JLabel getSurtirLbl() {
		return surtirLbl;
	}

	/**
	 * @return the imagenProducto
	 */
	public javax.swing.JLabel getImagenProducto() {
		return imagenProducto;
	}

	public JButton getCambiarFoto() {
		return cambiarFoto;
	}	
	
}
