/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpressosystems.xpresscashdrawer.view;

import com.xpressosystems.xpresscashdrawer.dao.VentaDAOFactory;
import com.xpressosystems.xpresscashdrawer.model.VentaTableModel;

/**
 *
 * @author alfredo
 */
public class PanelVentas extends javax.swing.JPanel {

	/**
	 * Creates new form PanelVenta
	 */
	public PanelVentas() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ventasJTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        ventasJTable.setModel(new VentaTableModel());
        jScrollPane1.setViewportView(ventasJTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));
        jPanel3.add(jPanel4);

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ventasJTable;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the ventasJTable
	 */
	public javax.swing.JTable getVentasJTable() {
		return ventasJTable;
	}

}
