INSERT INTO PREFERENCIA(ID,VALOR) VALUES ('BLUETOOTHADDRESS_PRINTER','00037A66B839');
INSERT INTO PREFERENCIA(ID,VALOR) VALUES ('NOMBRE_NEGOCIO','TIENDA DE ABARROTES');
INSERT INTO PREFERENCIA(ID,VALOR) VALUES ('DIRECCION_NEGOCIO','DOMICILIO CONOCIDO');
INSERT INTO PREFERENCIA(ID,VALOR) VALUES ('TELEFONOS_NEGOCIO','55-0000-0000,55-9999-9999');
INSERT INTO PREFERENCIA(ID,VALOR) VALUES ('CLIENTE_DEFAULT','CTE. MOSTRADOR');
INSERT INTO PREFERENCIA(ID,VALOR) VALUES ('EMAIL_NEGOCIO','some@mail.com');
